spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: develop
      server:
        git:
          uri: https://github.com/gannyee/Spring-Cloud/
          search-paths: respo
          username: ganyiwelldone@gmail.com
          password: gy542189475

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/