spring:
  application:
    name: hello-spring-cloud-eureka
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  instance:
    hostname: localhost  #eureka地址
  client:  #客户端
    registerWithEureka: false #做服务端改为false 使用Eureka服务端模式
    fetchRegistry: false #做服务端改为false 使用Eureka服务端模式
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

